# Generated by Django 5.0.6 on 2024-07-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(max_length=170),
        ),
    ]
